# Generated by Django 4.0.5 on 2022-07-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumemodel',
            name='city',
            field=models.CharField(choices=[('Delhi', 'Delhi'), ('Gurgaon', 'Gurgaon'), ('Noida', 'Noida'), ('Banglore', 'Banglore'), ('Pune', 'Pune'), ('Ranchi', 'Ranchi'), ('Mumbai', 'Mumbai'), ('Dhanbad', 'Dhanbad'), ('Bihar', 'Bihar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='mobile',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='resumemodel',
            name='pin',
            field=models.PositiveIntegerField(),
        ),
    ]
